### PR TITLE
Check ROCm library versions directly

### PR DESCRIPTION
**Pull request by cgmb**
There is no guarantee that the version number of the rocm-core library will match that of other ROCm libraries. It is both simpler and more robust to directly check the version number of the relevent library. For this reason, Debian has declined to package rocm-core. All other AMD GPU dependencies of magma are available in Debian Trixie.

The Debian builds of magama-rocm currently use libamdhip64-dev 5.7.1, libhipblas-dev 5.5.1, and libhipsparse-dev 5.7.1. The Ubuntu 24.04 LTS was frozen with those package versions in its universe repositories. There is no single value that could accurately describe the ROCM_VERSION on Debian or Ubuntu.

At the moment, a failure to find rocm-core is treated by magma as a version less than 6.0.0. Without this change, the Debian build of magma will begin to fail when either of the libamdhip64-dev or libhipblas-dev libraries are updated to a newer version.

### CODE REVIEW

**Comment by cgmb** [comment]
Marked as Ready for Review after building successfully using the system packages on Debian Unstable and using the official ROCm 6.3 on Ubuntu 24.04.

**Comment by prusnak** [comment]
@cgmb I am seeing this build error when trying to compile with ROCm 6.3

```
/build/magma-2.9.0/interface_hip/blas_z_v2.cpp:1853:9: error: no matching function for call to 'hipblasZtrmm'                                                                
        hipblasZtrmm(                                                                                                                                                        
        ^~~~~~~~~~~~                                                                                                                                                         
/nix/store/bnkf3d1df72ncbiy53xkpqizbjw7wdia-hipblas-6.0.2/include/hipblas/hipblas.h:17918:32: note: candidate function not viable: requires 14 arguments, but 12 were provide
d                                                                                                                                                                            
HIPBLAS_EXPORT hipblasStatus_t hipblasZtrmm(hipblasHandle_t             handle,                                                                                              
                               ^                                                                
```

coincidentally it is related to your change - you do not see the same build failure?

also I see another one here:

```
/build/magma-2.9.0/interface_hip/interface.cpp:546:34: error: no member named 'memoryType' in 'hipPointerAttribute_t'
                    return (attr.memoryType == hipMemoryTypeDevice);
```

**Comment by prusnak** [comment]
> it almost seems like `hipblasVersionMajor` and `HIP_VERSION_MAJOR` are not defined on my system

I am using ROcm 6.0.2, when I patch the script to always return `60002` - the build works

**Comment by LunNova** [comment]
I can repro the failure with hipblasZtrmm.

https://github.com/icl-utk-edu/magma/blob/5b1710a79b6561d5a221fbd82dbaa8d65a18f09c/interface_cuda/blas_z_v2.cpp#L1862-L1864

ROCM_VERSION is unset here so it doesn't add necessary additional arguments for 6.3.

**Comment by cgmb** [comment]
I cannot reproduce the problems you're seeing.

Here's proof that it builds just fine on ROCm 6.3.3. Start with `docker run -it --rm ubuntu:24.04`, then run the following commands:
```bash
cd ~
apt -y update
apt -y upgrade
apt install -y sudo gnupg2 wget vim git libopenblas-dev build-essential cmake gfortran
sudo mkdir --parents --mode=0755 /etc/apt/keyrings
wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.3.3 noble main" | sudo tee --append /etc/apt/sources.list.d/rocm.list
echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
apt -y update
apt install -y hipblas-dev hipsparse-dev rocm
git clone https://github.com/cgmb/magma.git -b rocm-version-check
cd magma
echo -e 'BACKEND = hip\nFORT = true\nGPU_TARGET = gfx906' > make.inc
sed -i '1s/python$/python3/' tools/codegen.py
make -j16 generate
export PATH="$PATH:/opt/rocm/bin"
CXX=hipcc cmake -S. -Bbuild -DBLA_VENDOR=OpenBLAS -DAMDGPU_TARGETS="gfx906" -DMAGMA_ENABLE_HIP=ON -DCMAKE_PREFIX_PATH=/opt/rocm
make -j 16 -C build
```

Here's a log showing a passing build: 
[magma-rocm-6.3-version-check.txt](https://github.com/user-attachments/files/19016320/magma-rocm-6.3-version-check.txt)

Here's proof that it builds just fine on a mix of ROCm 5.5 and ROCm 5.7. Start with `docker run -it --rm ubuntu:24.04`, run the following commands:

```bash
cd ~
apt -y update
apt -y upgrade
apt install -y git libopenblas-dev build-essential cmake gfortran hipcc libhipblas-dev libhipsparse-dev librocblas-dev librocsparse-dev
git clone https://github.com/cgmb/magma.git -b rocm-version-check
cd magma
echo -e 'BACKEND = hip\nFORT = true\nGPU_TARGET = gfx906' > make.inc
sed -i '1s/python$/python3/' tools/codegen.py
make -j16 generate
CXX=hipcc cmake -S. -Bbuild -DBLA_VENDOR=OpenBLAS -DAMDGPU_TARGETS="gfx906" -DMAGMA_ENABLE_HIP=ON
make -j 16 -C build
```

Here's a log showing a passing build:  [magma-rocm-5.x-version-check.txt](https://github.com/user-attachments/files/19016334/magma-rocm-5.x-version-check.txt)

> I can repro the failure with hipblasZtrmm.

The code you're quoting is not in my branch.

> So I guess this patch works only on recent versions of ROCm

No. [`hipblasVersionMajor` was introduced eight years ago.](https://github.com/ROCm/hipBLAS/blob/5d5ed367f0c714a9247ea6ab507ec002935bb7c3/library/include/hipblas-version.h.in) It has existed in every version of hipBLAS ever released.

**Comment by LunNova** [comment]
It works for me on icl-utk-edu:master which checks ROCM_VERSION, it's broken on this PR which checks hipblasVersionMajor, in the same way as for @prusnak

**Comment by prusnak** [comment]
> The code you're quoting is not in my branch.

it is - there is a macro which replaces `cublasZtrmm` with `hipblasZtrmm `

**Comment by cgmb** [comment]
I have provided a reproducible set of instructions. Please consider doing the same, as it is impossible for me to guess how you arrived at your results otherwise.

> it is - there is a macro which replaces `cublasZtrmm` with `hipblasZtrmm`

My branch is on commit 10fe816b763c41099fa1c978a79d6869246671cf, not 5b1710a79b6561d5a221fbd82dbaa8d65a18f09c. In my branch, those lines are:
https://github.com/icl-utk-edu/magma/blob/10fe816b763c41099fa1c978a79d6869246671cf/interface_cuda/blas_z_v2.cpp#L1862-L1864

**Comment by prusnak** [comment]
> My branch is on commit [10fe816](https://github.com/icl-utk-edu/magma/commit/10fe816b763c41099fa1c978a79d6869246671cf), not [5b1710a](https://github.com/icl-utk-edu/magma/commit/5b1710a79b6561d5a221fbd82dbaa8d65a18f09c). In my branch, those lines are:

We are applying the patch from this PR on top of 5b1710a79b6561d5a221fbd82dbaa8d65a18f09c

**Comment by LunNova** [comment]
Adding -H to see if hipblas-version.h is included shows it is and the define is in the exact file it used. Very confusing.

```
End of search list.
. /build/magma-2.9.0/control/magma_internal.h
.. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/stdlib.h
.. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/math.h
.. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/string.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/libc-header-start.h
... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/stddef.h
.... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/__stddef_null.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/strings.h
.... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/stddef.h
.. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/unistd.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/posix_opt.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/environments.h
.... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/wordsize.h
... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/stddef.h
.... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/__stddef_null.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/confname.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/getopt_posix.h
.... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/getopt_core.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/bits/unistd_ext.h
.... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/linux/close_range.h
.. /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/inttypes.h
... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/inttypes.h
.. /build/magma-2.9.0/control/pthread_barrier.h
.. /build/magma-2.9.0/include/magma_v2.h
... /build/magma-2.9.0/build/include/magma_config.h
... /build/magma-2.9.0/include/magmablas.h
.... /build/magma-2.9.0/include/magma_copy.h
..... /build/magma-2.9.0/include/magma_types.h
...... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/assert.h
...... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime.h
....... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/stdlib.h
....... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/assert.h
....... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/thread
........ /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/std_thread.h
......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/tuple
.......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/uses_allocator.h
.......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/unique_ptr.h
........ /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/this_thread_sleep.h
......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/chrono.h
.......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/ratio
........... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/cstdint
........... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
.......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/ctime
.......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/parse_numbers.h
.......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/cerrno
........ /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_common.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_runtime.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_common.h
........ /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/cstddef
......... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/stddef.h
......... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime_api.h
......... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/stddef.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/host_defines.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/driver_types.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/texture_types.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/channel_descriptor.h
........... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_channel_descriptor.h
............ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_vector_types.h
............. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/array
.............. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/compare
............... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
.............. /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/bits/version.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/surface_types.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_runtime_pt_api.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/hip_prof_str.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime_api.h
........... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/hip_prof_str.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_deprecated.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_gl_interop.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_atomic.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_device_functions.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/device_library_decls.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/hip_assert.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/math_fwd.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime_api.h
.......... /nix/store/06fvz1pi6s6w0d040jp6sc8lww741qja-rocmcxx/lib/clang/18/include/stddef.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_vector_types.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_warp_functions.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_warp_sync_functions.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_unsafe_atomics.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_surface_functions.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/texture_fetch_functions.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_texture_types.h
.......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/ockl_image.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/texture_indirect_functions.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/hip_ldg.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime_api.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_math_functions.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/hip_fp16_math_fwd.h
......... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_runtime.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime_api.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/library_types.h
...... /nix/store/03g0lzbk4pivmc5c5723xp517llcfd74-hipblas-6.3.3/include/hipblas/hipblas.h
....... /nix/store/03g0lzbk4pivmc5c5723xp517llcfd74-hipblas-6.3.3/include/hipblas/hipblas-export.h
....... /nix/store/03g0lzbk4pivmc5c5723xp517llcfd74-hipblas-6.3.3/include/hipblas/hipblas-version.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_complex.h
........ /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_complex.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_runtime_api.h
....... /nix/store/vxilqlg15f9ixfhvl8cvjidzp9yf7s56-hipblas-common-6.3.3/include/hipblas-common/hipblas-common.h
...... /nix/store/ychigbnacnjrbjvvlpq8bcpq74jxfmyf-hipsparse-6.3.3/include/hipsparse/hipsparse.h
....... /nix/store/ychigbnacnjrbjvvlpq8bcpq74jxfmyf-hipsparse-6.3.3/include/hipsparse/hipsparse-export.h
....... /nix/store/ychigbnacnjrbjvvlpq8bcpq74jxfmyf-hipsparse-6.3.3/include/hipsparse/hipsparse-version.h
...... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/hip_fp16.h
....... /nix/store/jr3x6yd277fnhsxwf0h4ssbbpxh1zi7k-clr-6.3.3/include/hip/amd_detail/amd_hip_fp16.h
........ /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/lib/gcc/x86_64-unknown-linux-gnu/14.2.1/../../../../x86_64-unknown-linux-gnu/include/assert.h
.... /build/magma-2.9.0/include/magmablas_z.h
.... /build/magma-2.9.0/include/magmablas_c.h
.... /build/magma-2.9.0/include/magmablas_d.h
.... /build/magma-2.9.0/include/magmablas_s.h
.... /build/magma-2.9.0/include/magmablas_zc.h
.... /build/magma-2.9.0/include/magmablas_ds.h
.... /build/magma-2.9.0/include/magmablas_h.h
... /build/magma-2.9.0/include/magma_batched.h
.... /build/magma-2.9.0/include/magma_zbatched.h
.... /build/magma-2.9.0/include/magma_cbatched.h
.... /build/magma-2.9.0/include/magma_dbatched.h
.... /build/magma-2.9.0/include/magma_sbatched.h
.... /build/magma-2.9.0/include/magma_hbatched.h
... /build/magma-2.9.0/include/magma_vbatched.h
.... /build/magma-2.9.0/include/magma_zvbatched.h
.... /build/magma-2.9.0/include/magma_cvbatched.h
.... /build/magma-2.9.0/include/magma_dvbatched.h
.... /build/magma-2.9.0/include/magma_svbatched.h
... /build/magma-2.9.0/include/magma_bulge.h
.... /build/magma-2.9.0/include/magma_zbulge.h
.... /build/magma-2.9.0/include/magma_cbulge.h
.... /build/magma-2.9.0/include/magma_dbulge.h
.... /build/magma-2.9.0/include/magma_sbulge.h
... /build/magma-2.9.0/include/magma_z.h
.... /build/magma-2.9.0/include/magma_zgehrd_m.h
... /build/magma-2.9.0/include/magma_c.h
.... /build/magma-2.9.0/include/magma_cgehrd_m.h
... /build/magma-2.9.0/include/magma_d.h
.... /build/magma-2.9.0/include/magma_dgehrd_m.h
... /build/magma-2.9.0/include/magma_s.h
.... /build/magma-2.9.0/include/magma_sgehrd_m.h
... /build/magma-2.9.0/include/magma_zc.h
... /build/magma-2.9.0/include/magma_ds.h
... /build/magma-2.9.0/include/magma_auxiliary.h
.... /nix/store/qxslsq8c3zaa8jd8qk9nsl08p7h17bi2-gcc-prefix/include/c++/math.h
... /build/magma-2.9.0/include/magma_htc.h
.. /build/magma-2.9.0/include/magma_lapack.h
... /build/magma-2.9.0/include/magma_mangling.h
.... /build/magma-2.9.0/include/magma_mangling_cmake.h
... /build/magma-2.9.0/include/magma_zlapack.h
... /build/magma-2.9.0/include/magma_clapack.h
... /build/magma-2.9.0/include/magma_dlapack.h
... /build/magma-2.9.0/include/magma_slapack.h
.. /build/magma-2.9.0/include/magma_operators.h
.. /build/magma-2.9.0/control/magma_threadsetting.h
. /build/magma-2.9.0/interface_hip/error.h
/build/magma-2.9.0/interface_hip/blas_z_v2.cpp:1853:9: error: no matching function for call to 'hipblasZtrmm'
 1853 |         hipblasZtrmm(
      |         ^~~~~~~~~~~~
/nix/store/03g0lzbk4pivmc5c5723xp517llcfd74-hipblas-6.3.3/include/hipblas/hipblas.h:26717:32: note: candidate function not viable: requires 14 arguments, but 12 were provided
 26717 | HIPBLAS_EXPORT hipblasStatus_t hipblasZtrmm(hipblasHandle_t             handle,
       |                                ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26718 |                                             hipblasSideMode_t           side,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26719 |                                             hipblasFillMode_t           uplo,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26720 |                                             hipblasOperation_t          transA,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26721 |                                             hipblasDiagType_t           diag,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26722 |                                             int                         m,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26723 |                                             int                         n,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26724 |                                             const hipblasDoubleComplex* alpha,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26725 |                                             const hipblasDoubleComplex* A,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26726 |                                             int                         lda,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26727 |                                             const hipblasDoubleComplex* B,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26728 |                                             int                         ldb,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26729 |                                             hipblasDoubleComplex*       C,
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 26730 |                                             int                         ldc);
       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx906.
failed to execute:/nix/store/z05bi8jkqn9l6nwz3hl3v15nvs3dba9v-rocm-llvm-merge/bin/clang++  --hip-device-lib-path="/nix/store/9g8hqgg0fsv2iba536ifixs92gkqisck-rocm-device-libs-6.3.1/amdgcn/bitcode"  -DUSE_PROF_API=1 -D__HIP_PLATFORM_AMD__=1 -Dmagma_EXPORTS -I/build/magma-2.9.0/build/include -I/build/magma-2.9.0/include -I/build/magma-2.9.0/control -I/build/magma-2.9.0/magmablas_hip -I/build/magma-2.9.0/sparse_hip/include -I/build/magma-2.9.0/sparse_hip/control -I/build/magma-2.9.0/testing -isystem /nix/store/03g0lzbk4pivmc5c5723xp517llcfd74-hipblas-6.3.3/include -isystem /nix/store/vxilqlg15f9ixfhvl8cvjidzp9yf7s56-hipblas-common-6.3.3/include -isystem /nix/store/ychigbnacnjrbjvvlpq8bcpq74jxfmyf-hipsparse-6.3.3/include -H -v -DADD_ -parallel-jobs=1 -std=c++14 -D__HIP_PLATFORM_AMD__ -Wall -Wno-unused-function -O3 -DNDEBUG -fPIC -x hip -MD -MT CMakeFiles/magma.dir/interface_hip/blas_z_v2.cpp.o -MF CMakeFiles/magma.dir/interface_hip/blas_z_v2.cpp.o.d -o "CMakeFiles/magma.dir/interface_hip/blas_z_v2.cpp.o" -c /build/magma-2.9.0/interface_hip/blas_z_v2.cpp
[323/3492] Building CXX object CMakeFiles/magma.dir/interface_hip/interface.cpp.o
FAILED: CMakeFiles/magma.dir/interface_hip/interface.cpp.o 

$ grep VersionMajor /nix/store/03g0lzbk4pivmc5c5723xp517llcfd74-hipblas-6.3.3/include/hipblas/hipblas-version.h
#define hipblasVersionMajor 2
```

**Comment by prusnak** [comment]
> Not your fault, nixpkgs issue.

Should I close this issue then?

**Review by LunNova — APPROVED** [review]

**Comment by mgates3** [comment]
Sounds like this is not needed anymore. Please comment or re-open if still needed.

**Comment by cgmb** [comment]
@mgates3, this is still needed. The discussion was about NixOS having difficulty applying the patch, but that just turned out to be due to differences between patching the git tree and patching the generated release tarball. The resolution of that discussion resulted in NixOS now including this change in their magma package.

It would be nice to get this change into magma itself so that distros no longer have to maintain a patch for it. (And, I think magma will find this version checking method easier too.)

Unfortunately, there doesn't seem to be a reopen button. I don't think I have permissions necessary to reopen this PR.

**Review by mgates3 — APPROVED** [review]
